name: Client CI

on:
    push:
        branches:
            - main
        paths:
            - "client/**"

jobs:
    build:
        name: Build
        defaults:
            run:
                working-directory: client
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: 8.14.3
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "pnpm"
                  cache-dependency-path: "client/pnpm-lock.yaml"
            - run: pnpm install
            - run: pnpm build
            - uses: actions/upload-artifact@v4
              with:
                  name: next-build
                  path: client/.next

    test:
        name: Test
        defaults:
            run:
                working-directory: client
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: 8.14.3
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "pnpm"
                  cache-dependency-path: "client/pnpm-lock.yaml"
            - run: pnpm install
            - run: pnpm test --watchAll=false
            - run: pnpm test:cov --watchAll=false
            - uses: actions/upload-artifact@v4
              with:
                  name: coverage-report
                  path: client/coverage

    # # Currently the test url is local host. Here we can pass TEST URL from env.
    # # But its not setup.
    # end-to-end-test:
    #     name: End-to-End Test
    #     defaults:
    #         run:
    #             working-directory: client
    #     timeout-minutes: 60
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v4
    #         - uses: pnpm/action-setup@v3
    #           with:
    #               version: 8.14.3
    #         - uses: actions/setup-node@v4
    #           with:
    #               node-version: "20"
    #               cache: "pnpm"
    #               cache-dependency-path: "client/pnpm-lock.yaml"
    #         - run: pnpm install
    #         - run: pnpm exec playwright install --with-deps
    #         - run: pnpm exec playwright test
    #         - uses: actions/upload-artifact@v4
    #           if: always()
    #           with:
    #               name: playwright-report
    #               path: client/playwright-report
    #               retention-days: 30
