"""add created_at and updated_at columns in style_filter table

Revision ID: 278dff1e363f
Revises: 6f73ef3ce735
Create Date: 2024-11-01 17:33:52.579153+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "278dff1e363f"
down_revision: Union[str, None] = "6f73ef3ce735"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "style_filters",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "style_filters",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.drop_column("users", "upload_consumed_updated_at")
    op.drop_column("users", "upload_consumed")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("upload_consumed", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column(
            "upload_consumed_updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("style_filters", "updated_at")
    op.drop_column("style_filters", "created_at")
    # ### end Alembic commands ###
