"""add reported filter list column in user table

Revision ID: f16f72bfffc4
Revises: 2cb4ce5113c7
Create Date: 2024-11-02 07:33:40.075350+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f16f72bfffc4"
down_revision: Union[str, None] = "2cb4ce5113c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "reported_filter_ids",
            sa.ARRAY(sa.Integer()),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "reported_filter_ids")
    # ### end Alembic commands ###
